import numpy as np
import matplotlib.pyplot as plt

def fixedpoint_with_stopping(g, p0, Nmax, TOL, p=None, C=None, k=None):
    """
    
    Using the fixed-point iteration method, this function solves the problem p = g(p)

    Args:
        :param g: The function which will be iterated over
        :param p0: The initial guess to the solution of p = g(p)
        :param Nmax: The maximum number of iterations over g
        :param TOL: The tolerance for the stopping criteria defined as |p_m - p_(m-1)| <= TOL
        :param p: The exact solution to p = g(p) if known, otherwise it is None
        :param C: One of the positive constants used to define the stopping criteria |p - p_n| <= CK^n 
        :param K: One of the positive constants used to define the stopping criteria |p - p_n| <= CK^n

    Returns:
        :numpy.ndarray called p_array with shape (m,) containing the iterates p_n generated by the fixed point iteration before
        reaching Nmax iterations or after the iterations hits Nmax

    Outputs:
        :(if p is known) a graph corresponding to the plot of the absolute error |p - p_n| using a logarithmic scale on the y-axis
        :(if C and k are provided) a plot of the error bound CK^n on the same graph as the above 
    
    """


    p_array = np.zeros(Nmax)
    
    #Write your code for fixed point iteration according to the instructions:

    p0 = g(p0)
    p_array[0] = p0

    n = 1
    while n < Nmax:
        p = g(p0)
        p_array[n] = p
        if(np.abs(p - p_array[n-1]) <= TOL):
            break
        p0 = p
        n += 1
    p_array = p_array[:n+2]
    return p_array

    # fig = ax = None

    # Write your code to generate plots according to the instructions:


    # if fig is not None and ax is not None:
    #     return p_array, fig, ax
    # else:
    #     return p_array
    
if __name__ == "__main__":
    g = lambda x: x**3
    p0=1.0
    Nmax=50
    TOL=1e-11
    p_array = fixedpoint_with_stopping(g,p0,Nmax,TOL)
    print(p_array)